name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@release/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: withnosoul/withnosoul.github.io
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm install && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist/
